### ISSUE TITLE
contact us page

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#1]
As I can see there is no contact us page in the project I want to make that page.
@shriya030  can i work on this issue under LGM-SOC'21

**Comment by shriya030** [comment]
Hi @kumarishalini6 The coding period is going to start from 10. I'll assign this issue to you on 10th. Is that okay?

**Comment by kumarishalini6** [comment]
Ya that fine I am just trying to be first  because I have seen the competition

**Comment by shriya030** [comment]
> Ya that fine I am just trying to be first because I have seen the competition

Can you tell me what you'll add to the contact us page? or any sample you can show?

**Comment by kumarishalini6** [comment]
I don't have the exact sample , I was thinking to make a container and add to input fields and thinking to follow this with the project theme color
![IMG_20210609_201316](https://user-images.githubusercontent.com/69043944/121376839-7bbd1f00-c95f-11eb-9bbd-22d57502648b.jpg)

**Comment by kumarishalini6** [comment]
If you want something else you can show me I would love to work on your idea too.

**Comment by kumarishalini6** [comment]
@shriya030 can I work on this issue??

**Comment by shriya030** [comment]
> @shriya030 can I work on this issue??

Can you text me on slack?

**Comment by kumarishalini6** [comment]
Ok

**Comment by RiyaGupta89** [comment]
May I work under this issue?

**Comment by shriya030** [comment]
@kumarishalini6 Go ahead! But do match the color scheme of this page with that of the website!
