### ISSUE TITLE
Adding FrameWorks

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#11]
I want to add react.js , django , flask , node in framework.
@shriya030  can i work on this issue under LGM-SOC21 .

**Comment by Hardikpoudel** [comment]
Can i work on this issue?
I can add

**Comment by kumarishalini6** [comment]
@shriya030  can you assign this issue to me??

**Comment by shriya030** [comment]
> @shriya030 can you assign this issue to me??

Yup! Follow the exact pattern as it is written in the frameworks.js and don't add more than 6 links in each category (Youtube, Github,..)
Less links are okay but quality content should be there in them.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
@shriya030 can you please tell me why we have 2 AngularJS  is there any specific reason??
Can I remove one of them .

**Comment by shriya030** [comment]
> @shriya030 can you please tell me why we have 2 AngularJS is there any specific reason??
> Can I remove one of them.

Pull the upstream and then make the required changes. I have made few changes in the Data folder. There is only one angularJS now. You can add other frameworks after that.

**Comment by kumarishalini6** [comment]
Ok
