### ISSUE TITLE
splash screen 

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#12]

**Comment by shriya030** [comment]
Splash screen as in?

**Comment by kumarishalini6** [comment]
I want to make an attractive  splash screen ( a screen appears before the real website when the)

**Comment by kumarishalini6** [comment]
> Splash screen as in?

I didn't understand what are you trying to say

**Comment by shriya030** [comment]
> I want to make an attractive splash screen ( a screen appears before the real website when the)

I think it's a kind of preloader feature right? or something else?

**Comment by kumarishalini6** [comment]
No it's not a preloader 
Preloader appears whenever the page refreshed
But the splash screen appears when the website starts

**Comment by shriya030** [comment]
> No it's not a preloader
> Preloader appears whenever the page refreshed
> But the splash screen appears when the website starts

Before making a pull request, do show me what kind of splash screen you have created.

**Comment by kumarishalini6** [comment]
This is called splashscreen 
https://user-images.githubusercontent.com/69043944/121470328-ac429e80-c9db-11eb-84ac-db676f7764d6.mp4

**Comment by kumarishalini6** [comment]
> > No it's not a preloader
> > Preloader appears whenever the page refreshed
> > But the splash screen appears when the website starts
> 
> Before making a pull request, do show me what kind of splash screen you have created.

Sure

**Comment by kumarishalini6** [comment]
I guess the pre loader is  better than splash screen , for now i am closing this issue . When pre loader added and i found any changes need i will work on that . Thanks
