### ISSUE TITLE
Add all social media in website 

### ISSUE THREAD

**Issue by Yash-Sakre** [shriya030/CS-Hut#13]
Add all the social media link to the website 

can I work on this issue under LGM-SOC21?

**Comment by RiyaGupta89** [comment]
Hi, I am interested in working on this issue. I am a participant of LGMsoc'21. May I work under this repository?

**Comment by rishabhrathore055** [comment]
@Yash-Sakre  pls assign me this issue.

**Comment by lucifer-here01** [comment]
can I work on this issue @Yash-Sakre
