### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Rutuj-Runwal** [shriya030/CS-Hut#15]
- Changing Homepage UI to a lighter tone and add a dark mode toggle switch

**Comment by shriya030** [comment]
Dark mode will be for the whole website not only for the home page. Can you do that?

**Comment by Rutuj-Runwal** [comment]
I will do it for the whole site👍🏻

**Comment by shriya030** [comment]
> I will do it for the whole site👍🏻

Isn't it better if we apply dark-light mode when the UI part of the site is done?

**Comment by Rutuj-Runwal** [comment]
Yaa it would be better....
So I could just do the other issue and wait till the UI is completed.Then we can get back to this....

**Comment by Rutuj-Runwal** [comment]
So should I let this issue be open till that time?....

**Comment by shriya030** [comment]
> So should I let this issue be open till that time?....

I'll assign it to you, you can do it later on :)

**Comment by shriya030** [comment]
@Rutuj-Runwal you can start working on it now.

**Comment by shriya030** [comment]
@Rutuj-Runwal any update?

**Comment by kumarishalini6** [comment]
@shriya030  if he is not available can I design UI ??

**Comment by Rutuj-Runwal** [comment]
@kumarishalini6 Yaa I am having some issues with it you can try...

**Comment by kumarishalini6** [comment]
> @kumarishalini6 Yaa I am having some issues with it you can try...

ok once i got assign then i'll start working

**Comment by shriya030** [comment]
@kumarishalini6 Okay go ahead!

**Comment by kumarishalini6** [comment]
@shriya030 I have my semester exam after that I'll start
