### ISSUE TITLE
Link About and About Us section

### ISSUE THREAD

**Issue by Amrutha1101** [shriya030/CS-Hut#16]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Please describe the behavior you are expecting.

# Current Behavior:

What is the current behavior?

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.

# Screenshots (optional):
Hey Shriya, I found that about and about us section is not linked. Can I work on this under LGM-SOC

**Comment by Amrutha1101** [comment]
Can you assign me this task?

**Comment by shriya030** [comment]
@Amrutha1101 someone is already working on this issue. 
If she's not able to do within 2-3 days, I'll assign it to you.

**Comment by Amrutha1101** [comment]
Sure!!
