### ISSUE TITLE
Open a link in a new tab

### ISSUE THREAD

**Issue by Amrutha1101** [shriya030/CS-Hut#17]
### **Feature request**:

A clear and concise description of the feature.

### **Is your feature request related to a problem? Please describe. (optional)**:

A clear and concise description of what the problem is.

### **Describe how this feature will be useful to our readers**:

A clear and concise description of how this feature will be useful for our other readers.

### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.
Hey Shriya , in frameworks , after clicking on a link it's better for a reader if it opens in a new tab for the efficient use.
I would like to work on this . Can u assign me this task under LGM-SOC?

**Comment by shriya030** [comment]
Okay! Go ahead @Amrutha1101
