### ISSUE TITLE
Feedback Form

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#20]
### **Describe the bug:**
No feed back form is available but maintained at the footer, I want to make that form.
![InkedCS Hut - Personal - Microsoft​ Edge 6_10_2021 08_07_31 PM_LI](https://user-images.githubusercontent.com/69043944/121545109-b1d9bd80-c9b6-11eb-8eb7-599d557b33a4.jpg)

**Comment by kumarishalini6** [comment]
@shriya030 can i work on this issue

**Comment by shriya030** [comment]
> @shriya030 can i work on this issue

Will you link it to some google form or something?

**Comment by rishabhrathore055** [comment]
@shriya030 pls assign me this issue.

**Comment by lucifer-here01** [comment]
I  can add very Attractive  responsive feedback from @kumarishalini6  assign this issue to me under LGM Soc'21 program

**Comment by shriya030** [comment]
> @shriya030 pls assign me this issue.

Work on this after #35 is resolved! 
It will become easy for you.

**Comment by rishabhrathore055** [comment]
@shriya030 sure

**Comment by shriya030** [comment]
> @shriya030 sure

@rishabhrathore055 You can start working on it!

**Comment by rishabhrathore055** [comment]
@shriya030 yupp
