### ISSUE TITLE
README.md file update

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#21]
### **Feature request**:
I want to update readme.md file by adding project Name , About , how to fork and start contribution and many more with images.

@shriya030 can i work on this issue.

**Comment by shriya030** [comment]
@kumarishalini6 I have updated README.md.
If you want to put something else in it, you can create an issue for that.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
@shriya030  There is something I want to update :--
1) installating part I want to show through ss
2)Adding opensource name
3) SS of home page

**Comment by shriya030** [comment]
> @shriya030 There is something I want to update :--
> 
> 1. installating part I want to show through ss
>    2)Adding opensource name
> 2. SS of home page

Okay!
Add one more thing that issues will be assigned on First Come First Serve Basis (FCFS)
