### ISSUE TITLE
Change the banner text

### ISSUE THREAD

**Issue by shriya030** [shriya030/CS-Hut#24]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

# Expected Behavior:

Meaningful text on the banner

# Current Behavior:

Sample text

# Solution:

Change the text on the banner to "Your Guide to learn and apply in-demand technologies, all under one HUT !!"

**Comment by shrutigrover25** [comment]
Please assign me this issue as a part of LGMSOC.

**Comment by anushruti11** [comment]
I would like to work on this

**Comment by shriya030** [comment]
@shrutigrover25 assigned!

**Comment by shriya030** [comment]
> I would like to work on this

I am assigning issues on First Come First Serve basis! 
You can find or create any other issue.
