### ISSUE TITLE
Update React JS in framework section.

### ISSUE THREAD

**Issue by ritik-vashist** [shriya030/CS-Hut#27]
Till now only Angular JS is updated on frameworks page i would like to add react JS card to the framework section.
@shriya030 ma,am could you assign this task to me with the starting directions under the LGMSOC'21 Section?

**Comment by shriya030** [comment]
Someone is already working on this. You can add 3-4 languages. Is that okay?

**Comment by ritik-vashist** [comment]
@shriya030  Ma'am

Could you tell me which language should i add??

**Comment by ritik-vashist** [comment]
@shriya030 ma'am
Shall i go ahead with java?

**Comment by shriya030** [comment]
> @shriya030 ma'am
> Shall i go ahead with java?

Add 3-4 languages (C, Java, Python, Go) so that I can assign you with a good level. 
Take care of the points I mentioned in the README.

**Comment by ritik-vashist** [comment]
Sure @shriya030 assign this task to me.
