### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by SamikshaSankar** [shriya030/CS-Hut#3]
1. Changing colour when scroll
2. adding padding property(add more space)
3. Anchor a navbar

please assign me @shriya030

**Comment by shriya030** [comment]
It's already changing color when scroll.
Can you explain the other two points?

**Comment by SamikshaSankar** [comment]
Okay..
for second add some space 
![new](https://user-images.githubusercontent.com/52104082/121388146-db6bf800-c968-11eb-8308-eeb7a87f61d4.jpg)

for 3 when I click About which is present in header it goes to the about Us section which is present in same page..just like that

**Comment by shriya030** [comment]
@SamikshaSankar Great! Go ahead!

**Comment by Hardikpoudel** [comment]
Can i work on this issue?
