### ISSUE TITLE
Database section

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#30]
### **To Reproduce:**

4. See an error

### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by shriya030** [comment]
Can you explain clearly?

**Comment by kumarishalini6** [comment]
We have 3card in tags page one of them is database which is empty 
I want to fill it as others by adding SQL, mongodb etc

**Comment by shriya030** [comment]
> We have 3card in tags page one of them is database which is empty
> I want to fill it as others by adding SQL, mongodb etc

Okay! Go ahead :) 
Do add 3-4 databases.
