### ISSUE TITLE
Adding Web Development resources

### ISSUE THREAD

**Issue by anushruti11** [shriya030/CS-Hut#34]
### **Feature request**:

In the resources section, I want to add web development resources and resources for learning various programming languages.

**Comment by shriya030** [comment]
> ### **Feature request**:
> In the resources section, I want to add web development resources and resources for learning various programming languages.

Web development itself contains many topics. You can add more languages if you want.

**Comment by ashutosh887** [comment]
Please assign this to me!
I can Add some Resources to the Best of my knowledge...
Thanks

**Comment by anushruti11** [comment]
> > ### **Feature request**:
> > In the resources section, I want to add web development resources and resources for learning various programming languages.
> 
> Web development itself contains many topics. You can add more languages if you want.

I would like to add frontend , CSS resources and also resources which can be helpful for learning different programming languages and include free as well as paid courses.

**Comment by shriya030** [comment]
> > > ### **Feature request**:
> > > In the resources section, I want to add web development resources and resources for learning various programming languages.
> > 
> > 
> > Web development itself contains many topics. You can add more languages if you want.
> 
> I would like to add frontend , CSS resources and also resources which can be helpful for learning different programming languages and include free as well as paid courses.

Okay go ahead and add HTML, CSS and any other 2 programming languages in the languages file.

**Comment by RiyaGupta89** [comment]
Can i work on this issue?

**Comment by shriya030** [comment]
Okay @RiyaGupta89 
Add HTML, CSS and any other 2 programming languages in the languages file.

**Comment by joshi-kaushal** [comment]
I really want to contribute to this!

**Comment by shriya030** [comment]
@RiyaGupta89 any update?

**Comment by RiyaGupta89** [comment]
@shriya030 Completed it, please have a look.
