### ISSUE TITLE
Content is repeated twice in Footer. I would like to remove the duplicate one and center the content in Footer

### ISSUE THREAD

**Issue by pallavi-1812** [shriya030/CS-Hut#35]
### **Describe the bug:**

Content is repeated twice in Footer. Please assign me this issue.

### **To Reproduce:**

4. See an error

### **Expected behavior:**

Centering the content after removing the duplicate

### **Screenshots:**

![Annotation 2021-06-14 144036](https://user-images.githubusercontent.com/67572675/121868368-87716280-cd1e-11eb-93f5-2dc2565545b2.png)

### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by ashutosh887** [comment]
Has this Issue been assigned to someone ?
I can work on it!

**Comment by RiyaGupta89** [comment]
May I work on this issue?

**Comment by lucifer-here01** [comment]
can I Work on this issue? I want to contribute to this openSource project.

**Comment by lucifer-here01** [comment]
I can fix this repeated content issue as I have rectified the reason for the issue. Please assign me @shriya030 to remove this bug.
