### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by SamikshaSankar** [shriya030/CS-Hut#4]
Redesign footer

**Comment by RiyaGupta89** [comment]
May I work under this issue?

**Comment by Hardikpoudel** [comment]
can i work on this issue?

**Comment by shriya030** [comment]
@SamikshaSankar Assigned.

**Comment by RituCs** [comment]
I would like to work on this issue under LGMSOC'21 if no one is working .Thank You!

**Comment by SamikshaSankar** [comment]
@RituCs I am working on this..may be Today or tomorrow I will make PR
