### ISSUE TITLE
Make contact us page responsive

### ISSUE THREAD

**Issue by SNEHAL311998** [shriya030/CS-Hut#40]
### **Describe the bug:**

The Contact us page is not responsive.

### **To Reproduce:**

1. Go to 'https://cs-hut.herokuapp.com/contactus'
2. Click on 'F12'
3. See an error. The contact us form is not responsive

### **Expected behavior:**

Would like to make it responsive on mobile screen

### **Screenshots:**

![cshut](https://user-images.githubusercontent.com/61999845/121996681-ac211500-cdc6-11eb-99f5-8d55d39ed0ff.JPG)

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by SNEHAL311998** [comment]
Can I work on this issue. I yes please assign me I would like to work on it

**Comment by shriya030** [comment]
@SNEHAL311998 Go ahead!
