### ISSUE TITLE
Updating contributing guidelines

### ISSUE THREAD

**Issue by ayushsoni1010** [shriya030/CS-Hut#42]
### **Feature request**:

Updating contributing guidelines

### **Is your feature request related to a problem? Please describe. (optional)**:

I want to add more information in the contributing.md file

### **Describe the solution you'd like**:

Adding for a perfect workflow :)

### **Describe how this feature will be useful to our readers**:

They will understand the guidelines more accurately.

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.
  Yes, I have checked

  
  These are the things I want to add to the file.
  Kindly assign me issue :)

![image](https://user-images.githubusercontent.com/76895975/122047807-2f119200-cdfe-11eb-80ec-824d99881dd4.png)

**Comment by shriya030** [comment]
Assigned! @ayushsoni1010
