### ISSUE TITLE
Add License section in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [shriya030/CS-Hut#46]
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

**Comment by ishitakapoor26** [comment]
@shriya030 pls assign this issue to me.

**Comment by shriya030** [comment]
@ishitakapoor26 Which license will you add?

**Comment by varshitha1707** [comment]
I can add an MIT license.
Please assign me this issue under LGMSOC'21

**Comment by shriya030** [comment]
> I can add an MIT license.
> Please assign me this issue under LGMSOC'21

@varshitha1707 Okay go ahead!
