### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [shriya030/CS-Hut#47]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@shriya030 pls assign this issue to me.

**Comment by ishitakapoor26** [comment]
Like this 

![score card](https://user-images.githubusercontent.com/78542333/122353293-8aae5d80-cf6d-11eb-93ad-149e9f45e487.PNG)

**Comment by aj3011** [comment]
Okay @ishitakapoor26 Go ahead!
Don't add an image, rather add in text form
