### ISSUE TITLE
Automatic updation of Copyright Year 

### ISSUE THREAD

**Issue by Shaishav0507** [shriya030/CS-Hut#48]
# Prerequisites:

Hey @shriya030 
I would like to add automatic updation of footer copyright year.
At present code we need to change everytime.
Please assign it to me.
Thanks

- [ ] I checked to make sure that this issue has not already been filed.

- [ ] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Please describe the behavior you are expecting.

# Current Behavior:

What is the current behavior?

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.

# Screenshots (optional):

**Comment by shriya030** [comment]
@Shaishav0507 Start working on this issue after #20 is resolved.

**Comment by shriya030** [comment]
@Shaishav0507 Assigned!
