### ISSUE TITLE
About & Resources Part

### ISSUE THREAD

**Issue by SamikshaSankar** [shriya030/CS-Hut#5]
1. Add resources in website
2. text-align in about section on Right Side

Please assigned me @shriya030

**Comment by shriya030** [comment]
@SamikshaSankar For the first part, link resources in the navbar to the tags page, and do 2nd part as it is.

**Comment by shriya030** [comment]
@SamikshaSankar any update?

**Comment by shriya030** [comment]
> @SamikshaSankar any update?

@SamikshaSankar ?

**Comment by SamikshaSankar** [comment]
> > @SamikshaSankar any update?
> 
> @SamikshaSankar ?

Sorry for late reply... within 5 days I will be completed this issue
