### ISSUE TITLE
add more badges and move them to the top

### ISSUE THREAD

**Issue by Umesh-01** [shriya030/CS-Hut#50]
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Move badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the user will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

# Current Behavior:

I think badges should be at the top of README.md file not in the middle. Here (see the image below) they are not looking good.

# Solution:

I will move them to the top and also will add some more badges so that the README.md file will look more interactive and awesome. 

# Screenshots (optional):

![image](https://user-images.githubusercontent.com/83420185/122444442-2bc50480-cfbe-11eb-9718-adf6c9795900.png)

**Comment by Umesh-01** [comment]
@shriya030 Should I make these changes??

**Comment by shriya030** [comment]
@Umesh-01 Assigned!
