### ISSUE TITLE
Design Logo for CS Hut

### ISSUE THREAD

**Issue by ishitakapoor26** [shriya030/CS-Hut#59]
Design Logo for CS Hut

**Comment by ishitakapoor26** [comment]
@shriya030 pls assign me this issue.

**Comment by shriya030** [comment]
@ishitakapoor26 logo is already there.

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 logo is already there.

@shriya030 Yeah but I want to redesign it.
