### ISSUE TITLE
Update Tags card

### ISSUE THREAD

**Issue by SamikshaSankar** [shriya030/CS-Hut#6]
Chages in style of cards

**Comment by shriya030** [comment]
Okay, go ahead! and do ask me on slack if you face any issues.
Whatever design you are going to implement, kindly show it to me first on slack and then implement it.

**Comment by shriya030** [comment]
@SamikshaSankar what's the update?

**Comment by SamikshaSankar** [comment]
@shriya030 due to exams I am not active..but I can try to complete this task ASAP

**Comment by shriya030** [comment]
> @shriya030 due to exams I am not active..but I can try to complete this task ASAP

Can you do it in the next 2-3 days?

**Comment by SamikshaSankar** [comment]
@shriya030 Yes

**Comment by Ciggzy1312** [comment]
If available I would like to work on it as a LGMSOC participant
