### ISSUE TITLE
Successful alert pop up feature for contact page "Send" button

### ISSUE THREAD

**Issue by ROHAN842** [shriya030/CS-Hut#60]
### **Feature request**:

A clear and concise description of the feature.

Alert will popup on submission of contact form with a confirmation message also user will be redirected to a fresh page without back end where success message will be displayed.

A clear and concise description of what the problem is.

As when user fills all the detail and clicks on "Send" button then site doesn't take any response.

I want to add an alert which will pops up and will tell the user that message was delivered successfully with a green tick along with I would also like to add a feature without back end with which user would be sent to a fresh new page on clicking Send Message button where the message will be written, lets say "Thank you for your submission , Return back ".

![image](https://user-images.githubusercontent.com/61961107/122671920-7c1eab00-d1e6-11eb-99b3-30b78f04769f.png)

**Comment by aj3011** [comment]
Assigned @ROHAN842

**Comment by ROHAN842** [comment]
Hey @aj3011 and @shriya030 I request you to kindly merge my PR
