### ISSUE TITLE
Bug in Language page 

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#63]
### **Describe the bug:**
In language page the word "language " is not visible and the logo of java is also not visible.
![InkedCS Hut - Personal - Microsoft​ Edge 6_22_2021 12_28_58 PM_LI](https://user-images.githubusercontent.com/69043944/122878857-afdffa80-d2e4-11eb-9c19-d9d6bb2a3b03.jpg)

**Comment by kumarishalini6** [comment]
@shriya030  can i work on this issue

**Comment by shriya030** [comment]
@kumarishalini6 You can start working on it, leave the java logo. Someone is working on it. Do the rest for all the tags.
