### ISSUE TITLE
Fix the programming languages logos

### ISSUE THREAD

**Issue by supzi-del** [shriya030/CS-Hut#65]
- [x] I checked to make sure that this issue has not already been filed.

- [ ] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Better logos for programming languages on languages page.

# Current Behavior:

What is the current behavior?
The C language logo has an unwanted background and is not clear, the Java logo is missing 
![Screenshot (272)](https://user-images.githubusercontent.com/78655439/122982292-50ebb580-d3b8-11eb-9b1e-e5589cf5e746.png)

# Solution:

Change the background images of logos

# Screenshots (optional):

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC.

**Comment by shriya030** [comment]
@supzi-del Assigned!
