### ISSUE TITLE
🐛Bug in Routing.

### ISSUE THREAD

**Issue by Vaibhav-afk** [shriya030/CS-Hut#70]
### **Bug description:**

When we click on `about` in Navbar from `contactus`  page it doesn't work it redirects to `https://cs-hut.herokuapp.com/contactus#ab`.

### **Expected behavior:**

When we click on `about` in Navbar from `contactus`  page it should redirects to `https://cs-hut.herokuapp.com/#ab`.

### **Screenshots:**

https://user-images.githubusercontent.com/67143938/123298282-f8422700-d535-11eb-8b55-f8da78f28787.mp4

**Comment by shriya030** [comment]
@Vaibhav-afk It's already done by someone. Clone it in your PC to check if some other thing is missing.

**Comment by Vaibhav-afk** [comment]
> @Vaibhav-afk It's already done by someone. Clone it in your PC to check if some other thing is missing.

@shriya030 Yeah I did , I have also made pull request related to this issue.

**Comment by shriya030** [comment]
> > @Vaibhav-afk It's already done by someone. Clone it in your PC to check if some other thing is missing.
> 
> @shriya030 Yeah I did , I have also made pull request related to this issue.

It was already assigned to someone else before you made a pull request.

**Comment by Vaibhav-afk** [comment]
@shriya030 Okay, no problem.
