### ISSUE TITLE
Change the Footer

### ISSUE THREAD

**Issue by khareyash05** [shriya030/CS-Hut#72]
### **Feature request**:

I would like to suggest a feature to change the footer 
As a mentor of this project I would like to open it to participants
Kindly assign Open to all label @shriya030 if you want this feature

**Comment by shriya030** [comment]
What change do you want to have in footer?

**Comment by khareyash05** [comment]
The current design I feel is not very attractive. participants can redesign the footer

**Comment by shriya030** [comment]
> The current design I feel is not very attractive. participants can redesign the footer

Footer is already redesigned by someone. I think you are looking at the previous one.

**Comment by khareyash05** [comment]
ohhh thanx! for informing me
