### ISSUE TITLE
Error 404 page

### ISSUE THREAD

**Issue by khareyash05** [shriya030/CS-Hut#73]
### **Feature request**:

A clear and concise description of the feature.

I would like to suggest an Error 404 page for the website 
As a mentor of this project I would like to open it to participants
Kindly assign Open to all label @shriya030 if you want this feature

**Comment by shriya030** [comment]
Sure!

**Comment by kumarishalini6** [comment]
Can I work on this

**Comment by shriya030** [comment]
> Can I work on this

@kumarishalini6 Yes go ahead!
