### ISSUE TITLE
Page transitions and animations between routes

### ISSUE THREAD

**Issue by Srijan1878** [shriya030/CS-Hut#79]
### **Feature request**:

A clear and concise description of the feature.
Implementation of a page transitions and animations between react-routes. The preloader will be limited just to the initial loading of the home page.
### **Is your feature request related to a problem? Please describe. (optional)**:

A clear and concise description of what the problem is.

### **Describe the solution you'd like**:

I would like to add sleek transitions between routes using react framer-motion library
### **Describe how this feature will be useful to our readers**:

A clear and concise description of how this feature will be useful for our other readers.
This feature will ensure a much more smooth experience to the viewer.
### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by khareyash05** [comment]
@Srijan1878 Please share a video of the work.
