### ISSUE TITLE
Images are not visible in framework page

### ISSUE THREAD

**Issue by kumarishalini6** [shriya030/CS-Hut#8]
![InkedCS Hut - Personal - Microsoft​ Edge 6_9_2021 08_28_40 PM_LI](https://user-images.githubusercontent.com/69043944/121379414-783e7f00-c8f0-11eb-9a08-e0e8bfa72833.jpg)
@shriya030 can i work on this issue

**Comment by shriya030** [comment]
I need to update that part. Images are not there in the json. I'll give the format for that too. 
For now I am closing this issue.
