### ISSUE TITLE
Add Documentation for React Component Libraries

### ISSUE THREAD

**Issue by khareyash05** [shriya030/CS-Hut#81]
Add documentation for famous React Component libraries like Material UI, React Bootstrap

**Comment by joshi-kaushal** [comment]
Is this still open? would love to contribute

**Comment by shriya030** [comment]
> Is this still open? would love to contribute

Yes go ahead!
https://github.com/shriya030/CS-Hut/pull/75 Refer to this PR to get clarity on how to add and follow the guidelines to add resources mentioned in the README.

**Comment by shriya030** [comment]
@joshi-kaushal Is it done?

**Comment by joshi-kaushal** [comment]
Sorry but I am still working on it.
I am adding tools like Reactstrap, Redux, Styled Components but there is not enough resources (just a website and quite a few YT Playlists) So I am confused what whould I do.
