### ISSUE TITLE
About Section Redirection Bug

### ISSUE THREAD

**Issue by abhijeet-chatterjee** [shriya030/CS-Hut#83]
### **Describe the bug:**

Redirection to About section from navbar while on other pages does not work.

### **To Reproduce:**

1. Go to 'Resources Page  or Contact Us'
2. Open the 'Navbar'
3. Select the 'About Us' tab
4. No redirection happens.

### **Expected behavior:**

On Clicking the AboutUs it should redirect to the Homepage and AboutUs Section.

### **Screenshots:**

Please follow the steps to reProduce.

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by deeola** [comment]
Hello @abhijeet007rocks8  I would love to work on this bug. Thank you.
